version: "3.1"

services:
  backend:
    build: ./python/
    restart: always
    environment:
      - TELLER_ENVIRONMENT=sandbox
      - CERT_PATH=certificate.pem
      - CERT_KEY_PATH=priv_key.pem
    
    ports:
      - 8001:8001

  frontend:
    build: .
    restart: always

    ports:
      - 8000:8000